-- ============================================================================
-- Contextuate Monitor - MySQL Schema
-- ============================================================================
--
-- Production-ready MySQL schema for persistent storage of monitor sessions
-- and events. This schema supports distributed Claude Code monitoring with
-- hierarchical session tracking and efficient event querying.
--
-- Requirements: MySQL 8.0+ (for native JSON support)
-- Engine: InnoDB (for ACID compliance and foreign keys)
-- Charset: utf8mb4 (for full Unicode support)
--
-- ============================================================================

-- Drop existing tables (in reverse dependency order)
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS sessions;

-- ============================================================================
-- Sessions Table
-- ============================================================================
--
-- Stores metadata for each Claude Code session, including hierarchical
-- relationships (parent/child sessions) and token usage tracking.
--
CREATE TABLE sessions (
  -- Primary identification
  session_id VARCHAR(255) PRIMARY KEY
    COMMENT 'Unique session identifier from Claude Code',

  -- Machine & environment context
  machine_id VARCHAR(255) NOT NULL
    COMMENT 'Hostname or unique machine identifier',
  working_directory TEXT NOT NULL
    COMMENT 'Working directory where session was initiated',

  -- Timing information (Unix timestamps in milliseconds)
  start_time BIGINT NOT NULL
    COMMENT 'Session start timestamp (Unix ms)',
  end_time BIGINT DEFAULT NULL
    COMMENT 'Session end timestamp (Unix ms), NULL if active',

  -- Session state
  status VARCHAR(20) NOT NULL DEFAULT 'active'
    COMMENT 'Session status: active, completed, error',

  -- Hierarchical relationships
  parent_session_id VARCHAR(255) DEFAULT NULL
    COMMENT 'Auto-detected parent session ID (from Task tool spawns)',
  manual_parent_session_id VARCHAR(255) DEFAULT NULL
    COMMENT 'User-overridden parent session ID (set via UI)',
  child_session_ids JSON NOT NULL DEFAULT (JSON_ARRAY())
    COMMENT 'Array of child session IDs spawned by this session',

  -- Agent & session classification
  agent_type VARCHAR(50) DEFAULT NULL
    COMMENT 'Agent type for sub-agents (e.g., "nexus", "canvas", "archon")',
  is_user_initiated BOOLEAN NOT NULL DEFAULT TRUE
    COMMENT 'True if user-initiated, false if spawned via Task tool',

  -- UI state
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE
    COMMENT 'Whether session is pinned to top of UI list',
  hidden BOOLEAN NOT NULL DEFAULT FALSE
    COMMENT 'Whether session is hidden from default view',
  label VARCHAR(255) DEFAULT NULL
    COMMENT 'Custom session name/label set by user',

  -- Token usage metrics
  token_usage_input BIGINT NOT NULL DEFAULT 0
    COMMENT 'Total input tokens consumed by session',
  token_usage_output BIGINT NOT NULL DEFAULT 0
    COMMENT 'Total output tokens generated by session',

  -- Audit timestamps
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    COMMENT 'Record creation timestamp',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    COMMENT 'Record last update timestamp',

  -- Constraints
  CONSTRAINT chk_status CHECK (status IN ('active', 'completed', 'error')),
  CONSTRAINT chk_end_time CHECK (end_time IS NULL OR end_time >= start_time),
  CONSTRAINT fk_parent_session FOREIGN KEY (parent_session_id)
    REFERENCES sessions(session_id) ON DELETE SET NULL,

  -- Indexes for common queries
  INDEX idx_status (status),
  INDEX idx_parent_session_id (parent_session_id),
  INDEX idx_start_time (start_time DESC),
  INDEX idx_machine_id (machine_id),
  INDEX idx_hidden_status (hidden, status, start_time DESC),
  INDEX idx_pinned (is_pinned, start_time DESC)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Claude Code session metadata with hierarchical tracking';

-- ============================================================================
-- Events Table
-- ============================================================================
--
-- Stores all monitor events (tool calls, messages, notifications, etc.) with
-- full event payload in JSON format. Optimized for chronological queries.
--
CREATE TABLE events (
  -- Primary identification
  id VARCHAR(36) PRIMARY KEY
    COMMENT 'UUID for this event',

  -- Session association
  session_id VARCHAR(255) NOT NULL
    COMMENT 'Session that generated this event',

  -- Timing
  timestamp BIGINT NOT NULL
    COMMENT 'Event timestamp (Unix ms)',

  -- Event classification
  event_type VARCHAR(50) NOT NULL
    COMMENT 'Event type: session_start, session_end, tool_call, tool_result, message, notification, thinking, error, agent_spawn, agent_complete',
  hook_type VARCHAR(50) NOT NULL
    COMMENT 'Claude hook type: PreToolUse, PostToolUse, Notification, Stop, SubagentStop',

  -- Context (denormalized for query performance)
  parent_session_id VARCHAR(255) DEFAULT NULL
    COMMENT 'Parent session ID at time of event',
  machine_id VARCHAR(255) NOT NULL
    COMMENT 'Machine ID at time of event',
  working_directory TEXT NOT NULL
    COMMENT 'Working directory at time of event',

  -- Full event payload
  data JSON NOT NULL
    COMMENT 'Complete event data: toolName, toolInput, toolOutput, message, thinking, tokenUsage, error, subagent',

  -- Audit timestamp
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    COMMENT 'Record creation timestamp',

  -- Constraints
  CONSTRAINT fk_event_session FOREIGN KEY (session_id)
    REFERENCES sessions(session_id) ON DELETE CASCADE,
  CONSTRAINT chk_event_type CHECK (event_type IN (
    'session_start', 'session_end', 'tool_call', 'tool_result',
    'message', 'notification', 'thinking', 'error',
    'agent_spawn', 'agent_complete'
  )),
  CONSTRAINT chk_hook_type CHECK (hook_type IN (
    'PreToolUse', 'PostToolUse', 'Notification', 'Stop', 'SubagentStop'
  )),

  -- Indexes for common query patterns
  -- Most common: get events for a session, newest first
  INDEX idx_session_timestamp (session_id, timestamp DESC),

  -- Cross-session recent events
  INDEX idx_timestamp (timestamp DESC),

  -- Event type filtering
  INDEX idx_event_type (event_type, timestamp DESC),

  -- Machine-specific queries
  INDEX idx_machine_timestamp (machine_id, timestamp DESC),

  -- Parent session tracking
  INDEX idx_parent_session (parent_session_id, timestamp DESC)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Claude Code monitor events with full JSON payloads';

-- ============================================================================
-- Optional: Partitioning Configuration
-- ============================================================================
--
-- For high-volume deployments (>10M events), consider partitioning the events
-- table by date range. Uncomment and adjust the following after table creation:
--
-- ALTER TABLE events
--   PARTITION BY RANGE (FLOOR(timestamp / 86400000)) (
--     PARTITION p_2025_01 VALUES LESS THAN (FLOOR(UNIX_TIMESTAMP('2025-02-01') * 1000 / 86400000)),
--     PARTITION p_2025_02 VALUES LESS THAN (FLOOR(UNIX_TIMESTAMP('2025-03-01') * 1000 / 86400000)),
--     PARTITION p_future VALUES LESS THAN MAXVALUE
--   );
--
-- Note: Partitioning requires updating partition definitions monthly/quarterly.
-- Consider implementing automated partition management for production use.

-- ============================================================================
-- Index Usage Notes
-- ============================================================================
--
-- sessions table:
--   - idx_status: Filter active/completed sessions
--   - idx_parent_session_id: Navigate session hierarchy
--   - idx_start_time: Sort sessions chronologically
--   - idx_hidden_status: Filter visible/hidden sessions
--   - idx_pinned: Sort pinned sessions to top
--
-- events table:
--   - idx_session_timestamp: PRIMARY query pattern (95% of queries)
--   - idx_timestamp: Cross-session "recent activity" view
--   - idx_event_type: Filter by event type (e.g., errors only)
--   - idx_machine_timestamp: Machine-specific monitoring
--   - idx_parent_session: Track events across session trees
--
-- ============================================================================
-- Migration & Maintenance
-- ============================================================================
--
-- To apply this schema:
--   1. Create database: CREATE DATABASE contextuate_monitor;
--   2. Select database: USE contextuate_monitor;
--   3. Run this script: source mysql-schema.sql;
--
-- To reset for testing:
--   DROP DATABASE IF EXISTS contextuate_monitor;
--   CREATE DATABASE contextuate_monitor;
--   USE contextuate_monitor;
--   source mysql-schema.sql;
--
-- Regular maintenance:
--   - Archive old events: DELETE FROM events WHERE timestamp < <threshold>;
--   - Vacuum deleted rows: OPTIMIZE TABLE events;
--   - Monitor index usage: SHOW INDEX FROM events;
--
-- ============================================================================
